# CustomisedMinecarts by WeilonYing
# Version 1.0

# Set a multiplier for maximum speed of a minecart. Default speed = 1.0
# WARNING! Minecart may derail if max_minecart_speed is greater than 1.65
max_minecart_speed: 1.0

# Set whether minecart will slow down automatically if it has no passenger.
slow_minecart_when_empty: true