# CustomisedMinecarts by WeilonYing
# Version 1.1

# === DEFAULT MINECART SETTINGS ===
# Set whether minecart will slow down automatically if it has no passenger.
slow_minecart_when_empty: true

# === MANIPULATOR BLOCKS ===
# To find block names, see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

# --- High Speed Block ---
highspeed_block:
    # Block name, e.g. STONE, GRASS etc.
    name: STAINED_CLAY
    
    # Block data, e.g. if name is LOG, and data is 1, this would be a spruce log
    data: 7 
    
    # Speed multiplier. Derailing may happen when if multiplier > 2 and minecart turns a corner
    multiplier: 1.5
    
# --- Slow Block ---
slow_block:
    # Block name, e.g. STONE, GRASS etc.
    name: STAINED_CLAY 
    
    # Block data, e.g. if name is LOG, and data is 1, this would be a spruce log
    data: 6
    
    # Speed multiplier. Derailing may happen when if multiplier > 2 and minecart turns a corner
    multiplier: 0.5 

# --- Normal Speed Block ---
# This block sets the speed of the minecart to the default max speed.
# Set normal speed block item
normal_speed_block:
    # Block name, e.g. STONE, GRASS etc.
    name: STONE 
    
    # Block data, e.g. if name is LOG, and data is 1, this would be a spruce log
    data: 0